apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "90"
  name: "postmottak"
  namespace: "aap"
  labels:
    "team": "aap"
spec:
  image: {{image}}
  port: 3000
  liveness:
    path: "/postmottak/api/internal/isAlive"
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/postmottak/api/internal/isReady"
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 4
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      memory: 512Mi
  azure:
    application:
      enabled: true
      allowAllUsers: true
  observability:
    tracing:
      enabled: true
  env:
  {{#each env}}
    - name: {{this.name }}
      value: {{this.value}}
  {{/each}}
  accessPolicy:
    inbound:
      rules:
        - application: kelvin-reverse-proxy
    outbound:
      rules:
        - application: postmottak-backend
        - application: behandlingsflyt
        - application: oppgave
      external:
        - host: "cdn.nav.no"
